### ISSUE TITLE
请问在线获取电话激活的CID是如何实现的？

### ISSUE THREAD

**Issue by cloudtom** [FHWWC/KeyCheck#2]
我看网页版页面上说“获取确认ID。由于服务器压力略大，暂时不开放。”请问这个功能是如何实现的，我想自己搭建一个用于激活，这样就不用对您的服务器造成太大压力了

**Comment by FHWWC** [comment]
和在线检测错误代码是一个原理，如果是桌面程序，套个webbrowser就可以了

**Comment by cloudtom** [comment]
请问大佬的意思是我要在服务器端用程序拨打微软的激活电话，然后用语音合成技术和微软客服说要进行电话激活，然后语音识别客服返回的CID吗？这未免太过于复杂了一点吧？是我理解错了吗？请大佬给指条明路

**Comment by FHWWC** [comment]
你写一个软件，通过webbrowser执行js获取cid，把它放到服务器上，然后你的网站通过socket连接服务器，调用软件让它获取到cid，获取结束后在用软件再通过服务器在发回到你的网站上，就可以了。
如果你仅仅想软件实现该功能，写好软件发布给用户就可以了，不建议桌面软件再去连接服务器。除非你不想让别人反编译你的源码，为起到保护目的放到服务器端还算是个理由。

**Comment by cloudtom** [comment]
那不是要向微软服务器发起请求才能获得CID吧？那相应的电话激活API接口是要去哪里寻找？微软有相关的开发文档吗？就是对应的用于电话激活的微软API接口地址（url）方便告知一下吗？就类似于这样的地址：http://www.microsoft.com/DRM/SL/BatchActivationRequest/1.0

**Comment by FHWWC** [comment]
微软的这个公开接口只能获取在线Key的确认ID.。

**Comment by FHWWC** [comment]
所有获取CID的源头是这些，这个网站关了所有的第三方获取CID的各种激活网站也得挂：https://pastebin.com/LCA3hkYE

**Comment by FHWWC** [comment]
如果只有在线的需求的话，向“http://www.microsoft.com/DRM/SL/BatchActivationRequest/1.0” 发送请求时把RequestType改为1就可以了，把纯数字的IID发送出去，返回纯数字的CID。

**Comment by cloudtom** [comment]
> 如果只有在线的需求的话，向“[http://www.microsoft.com/DRM/SL/BatchActivationRequest/1.0”](http://www.microsoft.com/DRM/SL/BatchActivationRequest/1.0%E2%80%9D) 发送请求时把RequestType改为1就可以了，把纯数字的IID发送出去，返回纯数字的CID。

感谢大佬的解答，但我还是有点不明白什么叫只有在线的需求？激活微软产品不都是要联网在线激活的吗？还有就是您提到的获取CID源头的网站和微软的“http://www.microsoft.com/DRM/SL/BatchActivationRequest/1.0” 这个接口有什么区别吗？还请大佬再次帮忙解答，谢谢大佬

**Comment by FHWWC** [comment]
那我也不知道为什么微软只公开了获取在线key的CID的接口，你可以去问微软。
另外给的那些链接是微软线下旗舰店的网站，应该是使用的内部接口，此网站也没有对外提供API，反正key不死就可以获取CID。我们都是通过在这个网站上运行Ajax请求或者纯执行js脚本获取CID（代替手动输入和点击按钮）。

**Comment by cloudtom** [comment]
我大概知道是怎么一回事了，不过大佬您发给我的网站貌似打不开了，不知道是我这边的原因还是网站失效了。然后就是微软的接口，我到处找都没找到有官方的文档。感觉要弄的话应该还是有点难度的，等我有空的时候再研究下该如何弄吧，谢谢大佬您的解答！

**Comment by FHWWC** [comment]
https://github.com/dadorner-msft/ActivationWs/tree/master/src/ActivationWs
参考这个项目。

我发的那几个网址可以更改DNS为 4.2.2.2 4.2.2.1 即可。
